# Generated by Django 3.0.7 on 2021-01-11 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sw_catalog', '0002_attributecategory_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemreview',
            options={'ordering': ['-created'], 'verbose_name': 'Відгук', 'verbose_name_plural': 'Відгуки'},
        ),
        migrations.AddField(
            model_name='itemreview',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='sw_catalog.ItemReview', verbose_name='Батьківський відгук'),
        ),
    ]
