# Generated by Django 3.2.8 on 2024-04-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrivatBankPaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(max_length=100, verbose_name='Ідентифікатор магазину')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль магазину')),
            ],
            options={
                'verbose_name': 'Налаштування оплати частинами ПриватБанку',
                'verbose_name_plural': 'Налаштування оплати частинами ПриватБанку',
            },
        ),
    ]
