# Generated by Django 3.2.8 on 2024-04-12 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sw_order', '0004_remove_orderstatus_name_ru'),
        ('part_payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateBankPartPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.CharField(max_length=10)),
                ('payment_state', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sw_order.order')),
            ],
            options={
                'verbose_name': 'Оплата частинами ПриватБанку',
                'verbose_name_plural': 'Оплати частинами ПриватБанку',
            },
        ),
    ]
