# Generated by Django 3.2.8 on 2024-07-17 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sw_catalog', '0007_auto_20240314_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPumbPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=False, verbose_name='Доступно для оплати Pumb')),
                ('min_payments_count', models.PositiveIntegerField(default=2, verbose_name='Мінімальна кількість платежів')),
                ('max_payments_count', models.PositiveIntegerField(default=24, verbose_name='Максимальна кількість платежів')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pumb_option', to='sw_catalog.item', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Опції оплати  для товару',
                'verbose_name_plural': 'Опції оплати частинами для товарів',
            },
        ),
    ]
