# Generated by Django 3.2.8 on 2024-03-14 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sw_content', '0002_auto_20240227_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='answer_ru',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='img',
            name='alt_ru',
        ),
        migrations.RemoveField(
            model_name='link',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='mailto',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='page',
            name='alt_ru',
        ),
        migrations.RemoveField(
            model_name='page',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='page',
            name='meta_descr_ru',
        ),
        migrations.RemoveField(
            model_name='page',
            name='meta_key_ru',
        ),
        migrations.RemoveField(
            model_name='page',
            name='meta_title_ru',
        ),
        migrations.RemoveField(
            model_name='page',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='alt_ru',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='tel',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='text',
            name='text_ru',
        ),
    ]
