# Generated by Django 3.2.8 on 2024-05-17 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sw_content', '0004_indexbannervideo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indexbannervideo',
            options={'verbose_name': 'Банерне відео головної сторінки'},
        ),
    ]
