# Generated by Django 3.2.8 on 2024-05-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sw_content', '0006_paymentmethodstext'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMethodsText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_description', models.TextField(verbose_name='Опис самовивозу')),
                ('nova_poshta_description', models.TextField(verbose_name='Опис доставки Новою поштою')),
                ('eleek_delivery_description', models.TextField(verbose_name='Опис доставки від Eleek')),
            ],
            options={
                'verbose_name': 'Описи методів доставки',
                'verbose_name_plural': 'Описи методів доставки',
            },
        ),
    ]
