# Generated by Django 3.2.8 on 2024-05-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sw_content', '0007_deliverymethodstext'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', verbose_name='Зображення карточки')),
                ('text', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Карточка на сторінці /shop',
                'verbose_name_plural': 'Карточки на сторінці /shop',
            },
        ),
    ]
