# Generated by Django 3.0.7 on 2020-09-14 14:44

import box.core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sw_global_config', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(blank=True, help_text='Kод для виводу в шаблоні', max_length=255, null=True, unique=True, verbose_name='Код')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, help_text='Відображення на сайті', verbose_name='Активність')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Створено')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Оновлено')),
                ('meta_title', models.TextField(blank=True, help_text='Заголовок сторінки в браузері, який відображається у видачі пошукових систем', null=True, verbose_name='Мета-заголовок')),
                ('meta_title_uk', models.TextField(blank=True, help_text='Заголовок сторінки в браузері, який відображається у видачі пошукових систем', null=True, verbose_name='Мета-заголовок')),
                ('meta_title_en', models.TextField(blank=True, help_text='Заголовок сторінки в браузері, який відображається у видачі пошукових систем', null=True, verbose_name='Мета-заголовок')),
                ('meta_title_ru', models.TextField(blank=True, help_text='Заголовок сторінки в браузері, який відображається у видачі пошукових систем', null=True, verbose_name='Мета-заголовок')),
                ('meta_descr', models.TextField(blank=True, help_text='__', null=True, verbose_name='Мета-опис')),
                ('meta_descr_uk', models.TextField(blank=True, help_text='__', null=True, verbose_name='Мета-опис')),
                ('meta_descr_en', models.TextField(blank=True, help_text='__', null=True, verbose_name='Мета-опис')),
                ('meta_descr_ru', models.TextField(blank=True, help_text='__', null=True, verbose_name='Мета-опис')),
                ('meta_key', models.TextField(blank=True, help_text='Список ключових слів', null=True, verbose_name='Ключові слова')),
                ('meta_key_uk', models.TextField(blank=True, help_text='Список ключових слів', null=True, verbose_name='Ключові слова')),
                ('meta_key_en', models.TextField(blank=True, help_text='Список ключових слів', null=True, verbose_name='Ключові слова')),
                ('meta_key_ru', models.TextField(blank=True, help_text='Список ключових слів', null=True, verbose_name='Ключові слова')),
                ('slug', models.SlugField(max_length=255, null=True, verbose_name='Посилання')),
                ('alt', models.CharField(blank=True, max_length=255, null=True, verbose_name='Альт до картинки')),
                ('alt_uk', models.CharField(blank=True, max_length=255, null=True, verbose_name='Альт до картинки')),
                ('alt_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Альт до картинки')),
                ('alt_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Альт до картинки')),
                ('image', models.ImageField(blank=True, null=True, storage=box.core.models.OverwriteStorage(), upload_to='', verbose_name='Картинка')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('title_uk', models.CharField(max_length=255, null=True, verbose_name='Назва')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Назва')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Назва')),
                ('description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Опис')),
                ('description_uk', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Опис')),
                ('description_en', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Опис')),
                ('description_ru', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Опис')),
                ('content', tinymce.models.HTMLField(null=True, verbose_name='Контент')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Публікація',
                'verbose_name_plural': 'Публікації',
                'ordering': ['-order'],
            },
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(blank=True, help_text='Kод для виводу в шаблоні', max_length=255, null=True, unique=True, verbose_name='Код')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, help_text='Відображення на сайті', verbose_name='Активність')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Створено')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Оновлено')),
                ('meta_title', models.TextField(blank=True, help_text='Заголовок сторінки в браузері, який відображається у видачі пошукових систем', null=True, verbose_name='Мета-заголовок')),
                ('meta_title_uk', models.TextField(blank=True, help_text='Заголовок сторінки в браузері, який відображається у видачі пошукових систем', null=True, verbose_name='Мета-заголовок')),
                ('meta_title_en', models.TextField(blank=True, help_text='Заголовок сторінки в браузері, який відображається у видачі пошукових систем', null=True, verbose_name='Мета-заголовок')),
                ('meta_title_ru', models.TextField(blank=True, help_text='Заголовок сторінки в браузері, який відображається у видачі пошукових систем', null=True, verbose_name='Мета-заголовок')),
                ('meta_descr', models.TextField(blank=True, help_text='__', null=True, verbose_name='Мета-опис')),
                ('meta_descr_uk', models.TextField(blank=True, help_text='__', null=True, verbose_name='Мета-опис')),
                ('meta_descr_en', models.TextField(blank=True, help_text='__', null=True, verbose_name='Мета-опис')),
                ('meta_descr_ru', models.TextField(blank=True, help_text='__', null=True, verbose_name='Мета-опис')),
                ('meta_key', models.TextField(blank=True, help_text='Список ключових слів', null=True, verbose_name='Ключові слова')),
                ('meta_key_uk', models.TextField(blank=True, help_text='Список ключових слів', null=True, verbose_name='Ключові слова')),
                ('meta_key_en', models.TextField(blank=True, help_text='Список ключових слів', null=True, verbose_name='Ключові слова')),
                ('meta_key_ru', models.TextField(blank=True, help_text='Список ключових слів', null=True, verbose_name='Ключові слова')),
                ('slug', models.SlugField(max_length=255, null=True, verbose_name='Посилання')),
                ('alt', models.CharField(blank=True, max_length=255, null=True, verbose_name='Альт до картинки')),
                ('alt_uk', models.CharField(blank=True, max_length=255, null=True, verbose_name='Альт до картинки')),
                ('alt_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Альт до картинки')),
                ('alt_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Альт до картинки')),
                ('image', models.ImageField(blank=True, null=True, storage=box.core.models.OverwriteStorage(), upload_to='', verbose_name='Картинка')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('title_uk', models.CharField(max_length=255, null=True, verbose_name='Назва')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Назва')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Назва')),
                ('description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Опис')),
                ('description_uk', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Опис')),
                ('description_en', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Опис')),
                ('description_ru', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sk', models.CharField(max_length=255)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='sw_blog.Post')),
            ],
            options={
                'verbose_name': 'Перегляд',
                'verbose_name_plural': 'Перегляди',
            },
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(blank=True, help_text='Kод для виводу в шаблоні', max_length=255, null=True, unique=True, verbose_name='Код')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, help_text='Відображення на сайті', verbose_name='Активність')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Створено')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Оновлено')),
                ('title', models.CharField(blank=True, max_length=120, null=True, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Коммент')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcomments', to='sw_blog.PostComment')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='sw_blog.Post')),
            ],
            options={
                'verbose_name': 'Коментар',
                'verbose_name_plural': 'Коментарі',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sw_blog.PostCategory', verbose_name='Категорія'),
        ),
        migrations.AddField(
            model_name='post',
            name='markers',
            field=models.ManyToManyField(blank=True, to='sw_global_config.GlobalMarker', verbose_name='Маркери'),
        ),
        migrations.AddField(
            model_name='post',
            name='similars',
            field=models.ManyToManyField(blank=True, null=True, to='sw_blog.Post', verbose_name='Схожі публікації'),
        ),
    ]
