# Generated by Django 3.2.8 on 2024-03-14 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sw_currency', '0002_auto_20240227_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='symbol_ru',
        ),
    ]
