# Generated by Django 3.2.8 on 2024-02-26 17:54

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sw_global_config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalconfig',
            name='from_email',
            field=models.CharField(blank=True, default='starway.notifier@gmail.com', help_text='Почта відправки листів', max_length=256, null=True, verbose_name='DEFAULT_FROM_EMAIL'),
        ),
        migrations.AlterField(
            model_name='globalconfig',
            name='host',
            field=models.CharField(blank=True, default='smtp.gmail.com', help_text='Сервер', max_length=256, null=True, verbose_name='EMAIL_HOST'),
        ),
        migrations.AlterField(
            model_name='globalconfig',
            name='password',
            field=models.CharField(blank=True, default='starway69018', help_text='Пароль', max_length=256, null=True, verbose_name='EMAIL_HOST_PASSWORD'),
        ),
        migrations.AlterField(
            model_name='globalconfig',
            name='username',
            field=models.CharField(blank=True, default='starway.notifier@gmail.com', help_text='Логін', max_length=256, null=True, verbose_name='EMAIL_HOST_USER'),
        ),
        migrations.AlterField(
            model_name='globaltag',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Колір'),
        ),
    ]
