# Generated by Django 3.2.8 on 2024-02-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sw_global_config', '0003_auto_20240227_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalconfig',
            name='password',
            field=models.CharField(blank=True, default='ipbqvhxkublskmkp', help_text='Пароль', max_length=256, null=True, verbose_name='EMAIL_HOST_PASSWORD'),
        ),
    ]
