# Generated by Django 3.2.8 on 2024-03-14 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sw_global_config', '0004_alter_globalconfig_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalconfig',
            name='og_image_rectangle_ru',
        ),
        migrations.RemoveField(
            model_name='globalconfig',
            name='og_image_square_ru',
        ),
        migrations.RemoveField(
            model_name='globallabel',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='globalmarker',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='globaltag',
            name='name_ru',
        ),
    ]
