# Generated by Django 3.0.7 on 2021-01-11 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20200914_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='sdf',
        ),
    ]
