# Generated by Django 3.2.8 on 2024-02-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_site_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='schedule_en',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Schedule'),
        ),
        migrations.AddField(
            model_name='site',
            name='schedule_ru',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Schedule'),
        ),
        migrations.AddField(
            model_name='site',
            name='schedule_uk',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Schedule'),
        ),
        migrations.AddField(
            model_name='siteaddress',
            name='title_en',
            field=models.CharField(max_length=256, null=True, verbose_name='Адреса'),
        ),
        migrations.AddField(
            model_name='siteaddress',
            name='title_ru',
            field=models.CharField(max_length=256, null=True, verbose_name='Адреса'),
        ),
        migrations.AddField(
            model_name='siteaddress',
            name='title_uk',
            field=models.CharField(max_length=256, null=True, verbose_name='Адреса'),
        ),
    ]
