# Generated by Django 3.2.8 on 2024-02-28 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20240228_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='Email')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='project.site', verbose_name='Налаштування')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
            },
        ),
    ]
