# Generated by Django 3.2.8 on 2024-02-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_siteemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesocial',
            name='link',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Посилання'),
        ),
        migrations.AlterField(
            model_name='sitesocial',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Текст'),
        ),
    ]
