# Generated by Django 3.2.8 on 2024-03-14 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20240228_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='alt_ru',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='alt_ru',
        ),
        migrations.RemoveField(
            model_name='site',
            name='schedule_ru',
        ),
        migrations.RemoveField(
            model_name='siteaddress',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='testdrivemodel',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='testdriveslider',
            name='alt_ru',
        ),
        migrations.RemoveField(
            model_name='testdriveslider',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='veloslider',
            name='alt_ru',
        ),
        migrations.RemoveField(
            model_name='veloslider',
            name='distance_ru',
        ),
        migrations.RemoveField(
            model_name='veloslider',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='veloslider',
            name='power_ru',
        ),
        migrations.RemoveField(
            model_name='veloslider',
            name='speed_ru',
        ),
    ]
