# Generated by Django 3.2.8 on 2024-03-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_indexblockone'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexBlockTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=512, verbose_name='Опис')),
                ('text1', models.CharField(max_length=512, verbose_name='Текст 1')),
                ('text2', models.CharField(max_length=512, verbose_name='Цифра 1')),
                ('text3', models.CharField(max_length=512, verbose_name='Од. вимірювання 1')),
                ('text4', models.CharField(max_length=512, verbose_name='Текст 2')),
                ('text5', models.CharField(max_length=512, verbose_name='Цифра 2')),
                ('text6', models.CharField(max_length=512, verbose_name='Од. вимірювання 2')),
                ('text7', models.CharField(max_length=512, verbose_name='Текст 3')),
                ('text8', models.CharField(max_length=512, verbose_name='Цифра 3')),
                ('text9', models.CharField(max_length=512, verbose_name='Од. вимірювання 3')),
                ('text10', models.CharField(max_length=512, verbose_name='Текст 4')),
                ('text11', models.CharField(max_length=512, verbose_name='Цифра 4')),
                ('text12', models.CharField(max_length=512, verbose_name='Од. вимірювання 4')),
                ('image', models.ImageField(max_length=512, upload_to='', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Головна - другий блок',
                'verbose_name_plural': 'Головна - другий блок',
            },
        ),
    ]
