# Generated by Django 3.2.8 on 2024-03-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_indexblockone'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexblockone',
            name='button_link',
            field=models.CharField(default='', max_length=512, verbose_name='Посилання'),
            preserve_default=False,
        ),
    ]
