# Generated by Django 3.2.8 on 2024-03-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_indexblockone_button_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexblockone',
            name='title',
            field=models.CharField(default='', max_length=512, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexblockone',
            name='title_en',
            field=models.CharField(max_length=512, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='indexblockone',
            name='title_uk',
            field=models.CharField(max_length=512, null=True, verbose_name='Заголовок'),
        ),
    ]
