# Generated by Django 3.2.8 on 2024-03-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_indexblocktwo'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexblocktwo',
            name='description_en',
            field=models.TextField(max_length=1024, null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='indexblocktwo',
            name='description_uk',
            field=models.TextField(max_length=1024, null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='indexblocktwo',
            name='text10_en',
            field=models.CharField(max_length=512, null=True, verbose_name='Текст 4'),
        ),
        migrations.AddField(
            model_name='indexblocktwo',
            name='text10_uk',
            field=models.CharField(max_length=512, null=True, verbose_name='Текст 4'),
        ),
        migrations.AddField(
            model_name='indexblocktwo',
            name='text11_en',
            field=models.CharField(max_length=512, null=True, verbose_name='Цифра 4'),
        ),
        migrations.AddField(
            model_name='indexblocktwo',
            name='text11_uk',
            field=models.CharField(max_length=512, null=True, verbose_name='Цифра 4'),
        ),
        migrations.AddField(
            model_name='indexblocktwo',
            name='text12_en',
            field=models.CharField(max_length=512, null=True, verbose_name='Од. вимірювання 4'),
        ),
        migrations.AddField(
            model_name='indexblocktwo',
            name='text12_uk',
            field=models.CharField(max_length=512, null=True, verbose_name='Од. вимірювання 4'),
        ),
        migrations.AddField(
            model_name='indexblocktwo',
            name='text1_en',
            field=models.CharField(max_length=512, null=True, verbose_name='Текст 1'),
        ),
        migrations.AddField(
            model_name='indexblocktwo',
            name='text1_uk',
            field=models.CharField(max_length=512, null=True, verbose_name='Текст 1'),
        ),
        migrations.AddField(
            model_name='indexblocktwo',
            name='text2_en',
            field=models.CharField(max_length=512, null=True, verbose_name='Цифра 1'),
        ),
        migrations.AddField(
            model_name='indexblocktwo',
            name='text2_uk',
            field=models.CharField(max_length=512, null=True, verbose_name='Цифра 1'),
        ),
        migrations.AddField(
            model_name='indexblocktwo',
            name='text3_en',
            field=models.CharField(max_length=512, null=True, verbose_name='Од. вимірювання 1'),
        ),
        migrations.AddField(
            model_name='indexblocktwo',
            name='text3_uk',
            field=models.CharField(max_length=512, null=True, verbose_name='Од. вимірювання 1'),
        ),
        migrations.AddField(
            model_name='indexblocktwo',
            name='text4_en',
            field=models.CharField(max_length=512, null=True, verbose_name='Текст 2'),
        ),
        migrations.AddField(
            model_name='indexblocktwo',
            name='text4_uk',
            field=models.CharField(max_length=512, null=True, verbose_name='Текст 2'),
        ),
        migrations.AddField(
            model_name='indexblocktwo',
            name='text5_en',
            field=models.CharField(max_length=512, null=True, verbose_name='Цифра 2'),
        ),
        migrations.AddField(
            model_name='indexblocktwo',
            name='text5_uk',
            field=models.CharField(max_length=512, null=True, verbose_name='Цифра 2'),
        ),
        migrations.AddField(
            model_name='indexblocktwo',
            name='text6_en',
            field=models.CharField(max_length=512, null=True, verbose_name='Од. вимірювання 2'),
        ),
        migrations.AddField(
            model_name='indexblocktwo',
            name='text6_uk',
            field=models.CharField(max_length=512, null=True, verbose_name='Од. вимірювання 2'),
        ),
        migrations.AddField(
            model_name='indexblocktwo',
            name='text7_en',
            field=models.CharField(max_length=512, null=True, verbose_name='Текст 3'),
        ),
        migrations.AddField(
            model_name='indexblocktwo',
            name='text7_uk',
            field=models.CharField(max_length=512, null=True, verbose_name='Текст 3'),
        ),
        migrations.AddField(
            model_name='indexblocktwo',
            name='text8_en',
            field=models.CharField(max_length=512, null=True, verbose_name='Цифра 3'),
        ),
        migrations.AddField(
            model_name='indexblocktwo',
            name='text8_uk',
            field=models.CharField(max_length=512, null=True, verbose_name='Цифра 3'),
        ),
        migrations.AddField(
            model_name='indexblocktwo',
            name='text9_en',
            field=models.CharField(max_length=512, null=True, verbose_name='Од. вимірювання 3'),
        ),
        migrations.AddField(
            model_name='indexblocktwo',
            name='text9_uk',
            field=models.CharField(max_length=512, null=True, verbose_name='Од. вимірювання 3'),
        ),
        migrations.AddField(
            model_name='indexblocktwo',
            name='title_en',
            field=models.CharField(max_length=512, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='indexblocktwo',
            name='title_uk',
            field=models.CharField(max_length=512, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='indexblockone',
            name='description',
            field=models.TextField(max_length=1024, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='indexblockone',
            name='description_en',
            field=models.TextField(max_length=1024, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='indexblockone',
            name='description_uk',
            field=models.TextField(max_length=1024, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='indexblocktwo',
            name='description',
            field=models.TextField(max_length=1024, verbose_name='Опис'),
        ),
    ]
