# Generated by Django 3.2.8 on 2024-05-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_auto_20240523_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='veloslider',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Посилання'),
        ),
    ]
