# Generated by Django 3.2.8 on 2024-06-11 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_auto_20240527_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdrive',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата створення'),
        ),
    ]
