# Generated by Django 3.2.8 on 2024-06-13 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_oferta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oferta',
            options={'verbose_name': 'Оферта', 'verbose_name_plural': 'Оферта'},
        ),
    ]
