# Generated by Django 3.2.8 on 2024-07-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_alter_oferta_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsettings',
            name='pumb_enabled',
            field=models.BooleanField(default=True, verbose_name='Pumb Bank Enabled'),
        ),
    ]
