# Generated by Django 3.2.8 on 2024-03-14 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sw_novaposhta', '0002_auto_20240227_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='region',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='type_ru',
        ),
        migrations.RemoveField(
            model_name='type',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='address_ru',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='title_ru',
        ),
    ]
