# Generated by Django 3.0.7 on 2020-09-14 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('constructor', '0001_initial'),
        ('sw_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='value',
            name='attr_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='constructor_values', to='sw_catalog.AttributeValue', verbose_name='Значення атрибуту товару'),
        ),
        migrations.AddField(
            model_name='value',
            name='parameter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.Parameter', verbose_name='Параметр'),
        ),
        migrations.AddField(
            model_name='value',
            name='value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='constructor_feature_values', to='sw_catalog.FeatureValue', verbose_name='Значення характеристики товару'),
        ),
        migrations.AddField(
            model_name='tabgroup',
            name='tab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.Tab', verbose_name='Вкладка'),
        ),
        migrations.AddField(
            model_name='tab',
            name='frame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.FrameType', verbose_name='Рама'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='children',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_relationships', to='constructor.Value'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_relationships', to='constructor.Value'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='attr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='constructor_parameters', to='sw_catalog.Attribute', verbose_name='Атрибут товару'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='constructor_features', to='sw_catalog.Feature', verbose_name='Характеристика товару'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='tab_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.TabGroup', verbose_name='Група'),
        ),
        migrations.AddField(
            model_name='frametype',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='sw_catalog.Item', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='framecolor',
            name='attribute_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sw_catalog.AttributeValue', verbose_name='Значення атрибута товара'),
        ),
        migrations.AddField(
            model_name='framecolor',
            name='frame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructor.FrameType', verbose_name='Рама'),
        ),
        migrations.AddField(
            model_name='constructorform',
            name='values',
            field=models.ManyToManyField(blank=True, to='constructor.Value', verbose_name='Вибрані елементи'),
        ),
        migrations.AlterUniqueTogether(
            name='value',
            unique_together={('code', 'parameter')},
        ),
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together={('parent', 'children')},
        ),
        migrations.AlterUniqueTogether(
            name='parameter',
            unique_together={('code', 'tab_group')},
        ),
    ]
