# Generated by Django 3.2.8 on 2024-02-26 17:54

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0002_auto_20210217_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='framecolor',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None, verbose_name='Колір'),
        ),
        migrations.AlterField(
            model_name='frametype',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None, verbose_name='Колір'),
        ),
        migrations.AlterField(
            model_name='value',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None, verbose_name='Колір'),
        ),
    ]
