# Generated by Django 3.2.8 on 2024-03-14 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sw_order', '0003_auto_20240227_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstatus',
            name='name_ru',
        ),
    ]
